### PR TITLE
Fix errors when event.data is object, not array

### PR DESCRIPTION
**Pull request by ETNOL**
Not entirely sure the root of this issue. I'm receiving an object back
from event.data in some of the onMessage events. There are already some
short-circuits for when the array doesn't contain the key. This adds a
check for indexOf prior to the call.

### CODE REVIEW

**Comment by andyburke** [comment]
Sorry, but it's very difficult to see the meat of this change with all the formatting changes. Please update the formatting to conform to the existing code if you'd like to continue to try to get this in.

**Comment by cardoni** [comment]
@andyburke: Heyo. Just saw this pull-request and wanted to share a cool trick.

> **NOTE**
>
> While this trick doesn't actually _do_ the work that you've requested from @ETNOL, it does certainly make life easier when you're in a PR diff, have a bunch of less-than-helpful spacing diffs highlighted, and merely want to make sense of the actual, substantive code changes.

## Ignore All _GH_ Whitespace Diffs

When viewing a _GH_ pull-request diff containing too many such tab/spacing change highlights, simply append a new **`w`** query-string (set to `1`/`true`) and reload the page:

```ruby
# and so...
https://github.com/honeinc/xdls/pull/1/files

# just becomes...
https://github.com/honeinc/xdls/pull/1/files?w=1
```

ka-blam!

### Example

| Before                                                                                                                                                                                                                                     | After                                                                                                                                                                                                                                         |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| <a href="https://github.com/honeinc/xdls/pull/1/files" target="_blank"><img class="aligncenter" alt="Before" src="https://user-images.githubusercontent.com/674107/29695171-148ed2a4-88f6-11e7-85ba-bc5b866c2457.png" width="200px" /></a> | <a href="https://github.com/honeinc/xdls/pull/1/files?w=1" target="_blank"><img class="aligncenter" alt="After" src="https://user-images.githubusercontent.com/674107/29695190-2fc41ba6-88f6-11e7-9384-100bfb607bf8.png" width="200px" /></a> |

**Comment by andyburke** [comment]
@cardoni cool trick, but I still wouldn't accept the PR with all the formatting changes :smile: 

@ETNOL I *would* accept the PR if you only make the substantive change

**Comment by andyburke** [comment]
resolved in https://github.com/honeinc/xdls/commit/c86f6cc74b0fd0a8115729804797b57cb4a0863c

**Pull request closed without merging**
